### ISSUE TITLE
Should handle nil user_agent

### ISSUE THREAD

**Issue by sstrumph** [jasonfb/universal_track_manager#31]
We've seen a few requests come through with a nil user_agent, resulting in the exception below.   We should just skip browser tracking in this situation without an exception.

```
gems/universal-track-manager-0.7.3/lib/universal_track_manager/controllers/concerns/universal_track_manager_concern.rb:30:in `user_agent': undefined method `[]' for nil:NilClass (NoMethodError)
    from gems/universal-track-manager-0.7.3/lib/universal_track_manager/controllers/concerns/universal_track_manager_concern.rb:60:in `track_visitor'
```

**Comment by jasonfb** [comment]
@sstrumph 

yes I agree with this. 

do you have reproduction scenario.  

or a test case, 

or at least maybe try to pull the user agent string as it comes through in the headers. Usually there is something like "`*/*`" ?

I agree the line could use a safe nil check because any user agent can be thrown at us from the wild world, but I just want to make sure we fix the right problem.
