### ISSUE TITLE
track_ips config isn't always respected

### ISSUE THREAD

**Issue by sstrumph** [jasonfb/universal_track_manager#35]
ip address is occasionally persisted even though track_ips config is set to false.

suspect this is happening in an evict_visits use case.

**Comment by jasonfb** [comment]
@sstrumph sorry didn't see these.

maybe the IP isn't in the request and so it thinks it's a different visit (thus evicting), which is technically by design, but it sniffs like the problem is in the request and/or the server. like, why would the request be able to be authenticated by Rail's session mechanism (which is what it all depends on), but have a missing IP?

Only explanation for same-session and different IP is when a user keeps their browser logged in and switches Wifi networks-- for example, if they move laptop from one location to another. for that use case the evict visit is the intended design.
